/**
 * VIP Hotels — the first STAY on the shared surface, and the first collection
 * whose filter grammar is genuinely different.
 *
 * The five retired atlases are journeys and voyages: brand, region, month,
 * ship, port, route. A hotel has none of that. It is one point with a category,
 * a loyalty program, a country and a city. So `supportsMonthFilter` and
 * `supportsStopFilter` are off, and the real axes are declared as descriptor
 * `facets` rather than branching the shared rail.
 *
 * PARAM TRAP, from the hotel atlas's own applyParams(): the UI axis labelled
 * "Brand / Program" is the `program` param — `tick("grp-brand","brands",
 * val("program"))` — while `brand` is a separate deep-link-only axis matching
 * the actual hotel brand. Wiring the visible control to `brand=` would break
 * every shared link.
 *
 * Source: public/maps/hotel/hotel-points.json, the same 2,501-point GeoJSON the
 * home globe already fetches. Generated by scripts/build-hotel-points.mjs in
 * prebuild, so this adds no new payload.
 */

import { fromLngLatPair, isFinitePair } from "@/lib/atlas/geo";
import { macroRegion, isCaribbeanCountry } from "./hotel-regions";
import { PROGRAM_DOMAINS } from "./hotel-programs";
import { hotelBrandDomain } from "./hotel-brands";
import type { AtlasFilterDescriptor, AtlasOffering } from "./types";

export const HOTEL_DESCRIPTOR: AtlasFilterDescriptor = {
  collection: "hotel",
  // Unused (stop filtering is off) but the shape requires them.
  stopParam: "location",
  stopRoleParam: "locationrole",
  roles: "journey",
  brandField: "brand",
  brandParam: "brand",
  supportsRegionExclusion: false,
  supportsVesselFilter: false,
  // `brand=` is deep-link-only (a hidden facet); no control writes it.
  supportsBrandFilter: false,
  idPrefix: "h_",
  // A hotel has no departure and no itinerary.
  supportsMonthFilter: false,
  supportsStopFilter: false,
  // `ids=` frames the shortlist without hiding the rest of the field, and `q`
  // is a raw substring over name/city/region/country. Both differ from the five.
  idsHighlightOnly: true,
  searchMode: "substring",
  extraIdParams: ["hotel"],
  facets: [
    { key: "category", param: "category", label: "Category", allLabel: "All categories" },
    // `program`, NOT `brand` — see the header note.
    { key: "program", param: "program", label: "Program", allLabel: "All programs" },
    { key: "country", param: "country", label: "Country", allLabel: "All countries" },
    // Deep-link-only, case-insensitive: no control offers these.
    { key: "brand", param: "brand", label: "Brand", allLabel: "All brands", hidden: true, ci: true },
    { key: "marqueeRegion", param: "region", label: "Collection", allLabel: "All", hidden: true, ci: true },
  ],
};

interface RawHotelFeature {
  geometry?: { coordinates?: [number, number] };
  properties?: {
    id?: string;
    name?: string;
    brand?: string | null;
    program?: string | null;
    category?: string | null;
    country?: string | null;
    city?: string | null;
    region?: string | null;
    marqueeRegion?: string | null;
  };
}
export interface RawHotelPoints {
  type?: string;
  features?: RawHotelFeature[];
}

export function adaptHotels(raw: RawHotelPoints): AtlasOffering[] {
  const out: AtlasOffering[] = [];
  for (const f of raw.features || []) {
    const p = f.properties || {};
    const id = p.id;
    if (!id) continue;
    const c = f.geometry?.coordinates;
    // A hotel with no coordinates cannot be browsed on a map; the point feed
    // only contains geocoded properties, so this is a guard, not a filter.
    if (!isFinitePair(c)) continue;
    const at = fromLngLatPair(c);

    // The visible region axis is the CURATED macro region derived from country,
    // not the feed's `region` (604 admin values) and not `marqueeRegion` (7
    // marketing keys). Getting this wrong would have put 604 pins on the globe.
    const macro = macroRegion(p.country);

    // `region=caribbean` also matches by country, per matchesRegionAlias().
    const marquee = [p.marqueeRegion, isCaribbeanCountry(p.country) ? "caribbean" : null]
      .filter(Boolean) as string[];

    out.push({
      id,
      // Feed ids are already `h_`-prefixed, so the prefixed form IS the id.
      idAliases: [id],
      collection: "hotel",
      title: p.name || "Hotel",
      brand: p.brand || null,
      brandLabel: p.brand || null,
      operator: p.brand || null,
      regions: macro ? [macro] : [],
      months: [],
      onDemand: false,
      window: null,
      startDate: null,
      endDate: null,
      days: null,
      departures: null,
      country: p.country || null,
      vessel: null,
      attributes: {
        category: p.category || null,
        program: p.program || null,
        country: p.country || null,
        brand: p.brand || null,
        marqueeRegion: marquee.length ? marquee : null,
      },
      // The card shows the BRAND's mark where the brand has one, and falls back
      // to the PROGRAM's mark (what the original card always showed) where it
      // does not. Keying on the program alone put the same virtuoso.com favicon
      // on 1,970 of 2,501 cards — see hotel-brands.ts.
      logoKey: (hotelBrandDomain(p.brand) ? p.brand : p.program) || null,
      // A hotel IS its single stop — that is what puts it on the map and what
      // the "See it in 3D" action flies to.
      stops: [{ name: p.name || "Hotel", region: macro, at }],
      path: [],
      itinerary: [],
      url: null,
      world: false,
      // EXACTLY the original haystack: name + city + region + country,
      // lowercased, matched by substring. Note `region` here IS the feed's
      // sub-national value — adding brand or program would silently widen
      // every search relative to the atlas being replaced.
      searchText: `${p.name || ""} ${p.city || ""} ${p.region || ""} ${p.country || ""}`.toLowerCase(),
    });
  }
  return out;
}
