/**
 * VIP Hotels — the first STAY on the shared surface, and the first collection
 * whose filter grammar is genuinely different.
 *
 * The five retired atlases are journeys and voyages: brand, region, month,
 * ship, port, route. A hotel has none of that. It is one point with a category,
 * a loyalty program, a country and a city. So `supportsMonthFilter` and
 * `supportsStopFilter` are off, and the real axes are declared as descriptor
 * `facets` rather than branching the shared rail.
 *
 * PARAM TRAP, from the hotel atlas's own applyParams(): the UI axis labelled
 * "Brand / Program" is the `program` param — `tick("grp-brand","brands",
 * val("program"))` — while `brand` is a separate deep-link-only axis matching
 * the actual hotel brand. Wiring the visible control to `brand=` would break
 * every shared link.
 *
 * Source: public/maps/hotel/hotel-points.json, the same 2,501-point GeoJSON the
 * home globe already fetches. Generated by scripts/build-hotel-points.mjs in
 * prebuild, so this adds no new payload.
 */

import { fromLngLatPair, isFinitePair } from "@/lib/atlas/geo";
import { macroRegion, isCaribbeanCountry } from "./hotel-regions";
import { PROGRAM_DOMAINS } from "./hotel-programs";
import { hotelBrandDomain } from "./hotel-brands";
import type { AtlasFilterDescriptor, AtlasOffering } from "./types";

export const HOTEL_DESCRIPTOR: AtlasFilterDescriptor = {
  collection: "hotel",
  // Unused (stop filtering is off) but the shape requires them.
  stopParam: "location",
  stopRoleParam: "locationrole",
  roles: "journey",
  brandField: "brand",
  brandParam: "brand",
  supportsRegionExclusion: false,
  supportsVesselFilter: false,
  // `brand=` is deep-link-only (a hidden facet); no control writes it.
  supportsBrandFilter: false,
  idPrefix: "h_",
  // A hotel has no departure, no itinerary and no length of its own.
  supportsMonthFilter: false,
  supportsStopFilter: false,
  supportsDurationFilter: false,
  // Hotels are the first collection with supplier offers attached; the cruise
  // and tour promotions in the same feed belong to the journey atlases.
  supportsPromotionFilter: true,
  // `ids=` frames the shortlist without hiding the rest of the field, and `q`
  // is a raw substring over name/city/region/country. Both differ from the five.
  idsHighlightOnly: true,
  searchMode: "substring",
  extraIdParams: ["hotel"],
  facets: [
    { key: "category", param: "category", label: "Category", allLabel: "All categories" },
    // `program`, NOT `brand` — see the header note.
    { key: "program", param: "program", label: "Program", allLabel: "All programs" },
    { key: "country", param: "country", label: "Country", allLabel: "All countries" },
    /*
     * City — the axis a traveller actually arrives with ("somewhere in Rome"),
     * and the one the rail could not offer because 2,475 hotels sit in 1,044
     * cities. `menuLimit` is what makes it offerable: the control waits until
     * the field is narrow enough for a menu to be readable, which one country
     * always achieves (the largest, the United States, has 189 cities).
     *
     * The adapter has written `city` into `attributes` since it was ported —
     * "the filter layer only reads attributes a facet declares" — so this line
     * is the whole feature: rail control, phone drawer, live counts, `?city=`
     * deep link, and its place in a shared link all come from the descriptor.
     */
    {
      key: "city",
      param: "city",
      label: "City",
      allLabel: "All cities",
      // One country is always enough: the widest, the United States, has 189.
      menuLimit: 200,
    },
    // Deep-link-only, case-insensitive: no control offers these.
    { key: "brand", param: "brand", label: "Brand", allLabel: "All brands", hidden: true, ci: true },
    { key: "marqueeRegion", param: "region", label: "Collection", allLabel: "All", hidden: true, ci: true },
  ],
};

interface RawHotelFeature {
  geometry?: { coordinates?: [number, number] };
  properties?: {
    id?: string;
    name?: string;
    brand?: string | null;
    program?: string | null;
    category?: string | null;
    country?: string | null;
    city?: string | null;
    region?: string | null;
    marqueeRegion?: string | null;
    /** Umbrella-resort search names from data/atlas/hotel/place-aliases.json. */
    alias?: string | null;
    /** Card-sized VIP amenity tags, from lib/atlas/hotel-perks.js at build. */
    perks?: string[];
    /** Property photograph. Present on every point, empty until Virtuoso. */
    thumb?: string | null;
    promo?: number;
  };
}
export interface RawHotelPoints {
  type?: string;
  features?: RawHotelFeature[];
}

export function adaptHotels(raw: RawHotelPoints): AtlasOffering[] {
  const out: AtlasOffering[] = [];
  for (const f of raw.features || []) {
    const p = f.properties || {};
    const id = p.id;
    if (!id) continue;
    const c = f.geometry?.coordinates;
    // A hotel with no coordinates cannot be browsed on a map; the point feed
    // only contains geocoded properties, so this is a guard, not a filter.
    if (!isFinitePair(c)) continue;
    const at = fromLngLatPair(c);

    // The visible region axis is the CURATED macro region derived from country,
    // not the feed's `region` (604 admin values) and not `marqueeRegion` (7
    // marketing keys). Getting this wrong would have put 604 pins on the globe.
    const macro = macroRegion(p.country);

    // `region=caribbean` also matches by country, per matchesRegionAlias().
    const marquee = [p.marqueeRegion, isCaribbeanCountry(p.country) ? "caribbean" : null]
      .filter(Boolean) as string[];

    out.push({
      id,
      // Feed ids are already `h_`-prefixed, so the prefixed form IS the id.
      idAliases: [id],
      collection: "hotel",
      title: p.name || "Hotel",
      brand: p.brand || null,
      brandLabel: p.brand || null,
      operator: p.brand || null,
      regions: macro ? [macro] : [],
      months: [],
      onDemand: false,
      window: null,
      startDate: null,
      endDate: null,
      days: null,
      departures: null,
      country: p.country || null,
      vessel: null,
      attributes: {
        category: p.category || null,
        program: p.program || null,
        country: p.country || null,
        brand: p.brand || null,
        marqueeRegion: marquee.length ? marquee : null,
        // Not a filter axis — nothing in the descriptor's `facets` names it.
        // It rides along so an "Ask The Guide" from a card can say WHERE the
        // property is, which is the first thing anyone asking about a hotel
        // means. The filter layer only reads attributes a facet declares, so an
        // extra key here cannot widen or narrow anything.
        city: p.city || null,
        /*
         * The VIP amenity block, reduced to at most three tags at build time
         * ("Daily breakfast · $100 credit · Room upgrade"). Like `city` it is
         * not a filter axis — no facet names it — it is what the card's benefit
         * line renders, and it is the closest thing a hotel card has to villa's
         * special-offer line. 2,270 of 2,475 properties have one.
         */
        perks: p.perks && p.perks.length ? p.perks : null,
      },
      // Empty on every hotel until the Virtuoso feed fills it; the card's media
      // slot renders nothing for null, so this is inert until it is not.
      thumb: p.thumb || null,
      hasPromotion: p.promo === 1,
      // The card shows the BRAND's mark where the brand has one, and falls back
      // to the PROGRAM's mark (what the original card always showed) where it
      // does not. Keying on the program alone put the same virtuoso.com favicon
      // on 1,970 of 2,501 cards — see hotel-brands.ts.
      logoKey: (hotelBrandDomain(p.brand) ? p.brand : p.program) || null,
      // A hotel IS its single stop — that is what puts it on the map and what
      // the "See it in 3D" action flies to.
      stops: [{ name: p.name || "Hotel", region: macro, at }],
      path: [],
      itinerary: [],
      url: null,
      world: false,
      // The original haystack — name + city + region + country, lowercased and
      // matched by substring — plus the point's `alias`, the only addition.
      // `region` here IS the feed's sub-national value; adding brand or program
      // would silently widen every search relative to the atlas replaced.
      // `alias` widens it on purpose, for six properties whose postal town is
      // not what anyone searches (Snowmass Village -> "aspen").
      searchText: `${p.name || ""} ${p.city || ""} ${p.region || ""} ${p.country || ""} ${p.alias || ""}`
        .toLowerCase(),
    });
  }
  return out;
}
