// GENERATED by scripts/build-collection-counts.mjs — do not edit by hand.
//
// How many records each collection ships, counted through the SAME adapters its
// atlas uses. lib/atlas-config.ts reads this for `count`, which the Explore
// menu, the home headline, the blurb and the map overlay line all state out
// loud — so the number the menu offers and the number that collection's filter
// rail reproduces are the same arithmetic over the same rows.
//
// The rail additionally hides departures that have already sailed, a cutoff
// that moves daily; these are catalogue counts, so between deploys the rail can
// read lower by however many have passed. `npm run build:collection-counts --
// --report` prints today's gap.
//
// 11,918 records across 8 collections.
export const COLLECTION_COUNTS = {
  hotel: 2240,
  villa: 3902,
  cruise: 4295,
  worldcruise: 311,
  safari: 450,
  train: 128,
  yacht: 467,
  jet: 125,
} as const;
